[puerto_rico]
icao_match = "^T[IJ][A-Z]{2}$"
utc_standard = -4
# no DST
iana = "America/Puerto_Rico"

[eastern]
icao_match = "^K[A-Z]{3}$"
utc_standard = -5
utc_daylight = -4
iana = "America/New_York"

[central]
icao_match = "^K[A-Z]{3}$"
utc_standard = -6
utc_daylight = -5
iana = "America/Chicago"

[mountain]
icao_match = "^K[A-Z]{3}$"
utc_standard = -7
utc_daylight = -6
iana = "America/Denver"

[mountain_nodst]
icao_match = "^K[A-Z]{3}$"
utc_standard = -7
# no DST
iana = "America/Phoenix"

[pacific]
icao_match = "^K[A-Z]{3}$"
utc_standard = -8
utc_daylight = -7
iana = "America/Los_Angeles"

[alaska]
icao_match = "^P[AFOP][A-Z]{2}$"
utc_standard = -9
utc_daylight = -8
iana = "America/Juneau"

[aleutian]
icao_match = "^PA[A-Z]{2}$"
utc_standard = -10
utc_daylight = -9
iana = "America/Adak"

[hawaii]
icao_match = "^P[A-Z]{3}$"
utc_standard = -10
# no DST
iana = "Pacific/Honolulu"

[tern_island]
icao_match = "^P[A-Z]{3}$"
utc_standard = -11
# no DST
iana = "Pacific/Midway"

[american_samoa]
icao_match = "^N[A-Z]{3}$"
utc_standard = -11
# no DST
iana = "Pacific/Pago_Pago"

[kiritimati]
icao_match = "^P[A-Z]{3}$"
utc_standard = 14
# no DST
iana = "Pacific/Kiritimati"

[marshall_islands]
icao_match = "^P[A-Z]{3}$"
utc_standard = 12
# no DST
iana = "Pacific/Tarawa"

[micronesia]
icao_match = "^PT[A-Z]{2}$"
utc_standard = 11
# no DST
iana = "Pacific/Kosrae"

[micronesia_chuuk]
icao_match = "^PT[A-Z]{2}$"
utc_standard = 10
# no DST
iana = "Pacific/Port_Moresby"

[guam]
icao_match = "^PG[A-Z]{2}$"
utc_standard = 10
# no DST
iana = "Pacific/Guam"

[palau]
icao_match = "^PT[A-Z]{2}$"
utc_standard = 9
# no DST
iana = "Pacific/Palau"

[east_labrador]
icao_match = "^C[A-Z]{3}$"
utc_standard = -4
utc_daylight = -3
iana = "America/Goose_Bay"

[quebec]
icao_match = "^C[A-Z]{3}$"
utc_standard = -5
utc_daylight = -4
iana = "America/Toronto"

[manitoba]
icao_match = "^C[A-Z]{3}$"
utc_standard = -6
utc_daylight = -5
iana = "America/Winnipeg"

[saskatchewan]
icao_match = "^C[A-Z]{3}$"
utc_standard = -6
# no DST
iana = "America/Regina"

[alberta]
icao_match = "^C[A-Z]{3}$"
utc_standard = -7
utc_daylight = -6
iana = "America/Edmonton"

[british_columbia]
icao_match = "^C[A-Z]{3}$"
utc_standard = -8
utc_daylight = -7
iana = "America/Vancouver"
